jobs:
    main:
        image: centos:7
        steps:
            - yum install -y sudo perl-Test-Base perl-Test-Differences perl-Test-Simple
            - ./easybutton-build.sh
            - export PATH=/data/moloch/bin:$PATH make install
            - cp -r capture/plugins/lua/samples /data/moloch/lua
            - (cd tests ; ./tests.pl)
            - (cd viewer; npm install ; npm test)

