jobs:
    main:
        image: centos:7
        steps:
            - mkdir -p /data/moloch/bin /data/moloch/etc
            - yum install -y sudo
            - ls -lR /data
            - ./easybutton-build.sh
            - make install

