jobs:
    main:
        image: centos:7
        steps:
            - mkdir -p /data/moloch/bin /data/moloch/etc
            - yum install -y sudo
            - ./easybutton-build.sh
            - export PATH=/data/moloch/bin:$PATH make install
            - ls -lR /data
            - (cd tests ; ./tests.pl)

